// QUIZ LIST
export const FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'
// QUIZ CREATOR
export const CHANGE_QUESTION = 'CHANGE_QUESTION'
export const CHANGE_RIGHT_ANSWER = 'CHANGE_RIGHT_ANSWER'
export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'
export const ADD_QUESTION = 'ADD_QUESTION'
export const RESET_QUIZ_CREATOR = 'RESET_QUIZ_CREATOR'
// AUTH
export const SET_FORM_CONTROLS = 'SET_FORM_CONTROLS'
// APP
export const SET_AUTHORIZED = 'SET_AUTHORIZED'
// QUIZ
export const SET_QUESTIONS_AND_LOADING = 'SET_QUESTIONS_AND_LOADING'
export const SET_ANSWERED_QUESTIONS = 'SET_ANSWERED_QUESTIONS'
export const ENCREASE_CURRENT_QUESTION = 'ENCREASE_CURRENT_QUESTION'
export const SET_ISFINISHED = 'SET_ISFINISHED'
export const REFRESH = 'REFRESH'
